# Generated by Django 4.2 on 2023-04-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
